name: myEduApp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:

    sdk: flutter
    
  cupertino_icons: ^1.0.0
  firebase_core: ^0.7.0 
  firebase_storage: ^7.0.0
  flutter_pdfview: ^1.0.4
  custom_splash: ^0.0.2
  connectivity: ^2.0.2
  data_connection_checker: ^0.3.4
  firebase_auth: ^0.20.1
  day_night_theme_flutter: ^0.0.4
  provider: ^4.0.3
  shared_preferences: ^0.5.6+1
  percent_indicator: ^2.1.3
  http: ^0.12.2
  provider_architecture: ^1.0.6
  universal_html: ^1.2.2
  path_provider: ^1.6.5
  fluttertoast: ^3.1.3
  flushbar: ^1.10.4
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
        uses-material-design: true
        assets:     
               - assets/images/
        fonts:
         - family: Kufi
           fonts:
            - asset: fonts/Droid.Arabic.Kufi_.ttf